export const companyData = [
    {"symbol":"NVDA",	    "name": "NVIDIA Corporation", "industry": "Semiconductors",	"marketCap": "3,601.52B"},
    { "symbol":"AAPL",	    "name": "Apple Inc.",	"industry": "Consumer Electronics",	"marketCap": "3,450.64B"},
    { "symbol":"MSFT",  "name":	"Microsoft Corporation",	"industry":"Software - Infrastructure", "marketCap": "3,106.22B"},
    { "symbol":"GOOG",  "name":	"Alphabet Inc.",	"industry":"Internet Content & Information",	"marketCap": "2,243.94B"},
    { "symbol":"GOOGL",     "name":	"Alphabet Inc.",	"industry":"Internet Content & Information",	"marketCap": "2,235.41B"},
    { "symbol":"AMZN",  "name":	"Amazon.com, Inc.",	"industry":"Internet Retail",	"marketCap": "2,151.48B"},
    { "symbol":"META",  "name":	"Meta Platforms, Inc.",	"industry":"Internet Content & Information",	"marketCap": "1,416.47B"},
    { "symbol":"TSLA",  "name":	"Tesla, Inc.",	"industry":"Auto Manufacturers",	"marketCap": "1,110.68B"},
    { "symbol":"BRK.A",     "name":	"Berkshire Hathaway Inc.",	"industry":"Insurance - Diversified",	"marketCap": "1,012.33B"},
    { "symbol":"BRK.B",     "name":	"Berkshire Hathaway Inc.",	"industry":"Insurance - Diversified",	"marketCap": "1,011.43B"},
    { "symbol":"TSM",   "name":	"Taiwan Semiconductor Manufacturing Company Limited",	"industry":"Semiconductors",	"marketCap":"832.59B" },
    { "symbol":"AVGO",  "name":	"Broadcom Inc.",	"industry":"Semiconductors",	"marketCap":"772.28B" },
    { "symbol":"WMT",   "name":	"Walmart Inc.",	"industry":"Discount Stores",	"marketCap":"696.11B"},
    { "symbol":"JPM",   "name":	"JPMorgan Chase & Co.",	"industry":"Banks - Diversified",	"marketCap":"684.38B"},
    { "symbol":"LLY",   "name":	"Eli Lilly and Company",	"industry":"Drug Manufacturers - General",	"marketCap":"657.07B"},
    { "symbol":"V",     "name":	"Visa Inc.",	"industry":"Credit Services",	"marketCap":"611.14B"},
    { "symbol":"UNH",   "name":	"UnitedHealth Group Incorporated",	"industry":"Healthcare Plans",	"marketCap":"531.00B"},
    { "symbol":"ORCL",  "name":	"Oracle Corporation",	"industry":"Software - Infrastructure",	"marketCap":"523.45B"},
    { "symbol":"XOM",   "name":	"Exxon Mobil Corporation",	"industry":"Oil & Gas Integrated",	"marketCap":"521.39B"},
    { "symbol":"MA",    "name":	"Mastercard Incorporated",	"industry":"Credit Services",	"marketCap":"476.78B"},
    { "symbol":"NVO",   "name":	"Novo Nordisk A/S",	"industry":"Drug Manufacturers - General",	"marketCap":"455.78B"},
    { "symbol":"COST",  "name":	"Costco Wholesale Corporation",	"industry":"Discount Stores",	"marketCap":"412.12B"},
    { "symbol":"HD",    "name":	"The Home Depot, Inc.",	"industry":"Home Improvement Retail",	"marketCap":"404.07B"},
    { "symbol":"PG",    "name":	"The Procter & Gamble Company",	"industry":"Household & Personal Products",	"marketCap":"402.15B"},
    { "symbol":"NFLX",  "name":	"Netflix, Inc.",	"industry":"Entertainment",	"marketCap":"372.45B"},
    { "symbol":"JNJ",   "name":	"Johnson & Johnson",	"industry":"Drug Manufacturers - General",	"marketCap":"368.37B"},
    { "symbol":"BAC",   "name":	"Bank of America Corporation",	"industry":"Banks - Diversified",	"marketCap":"356.10B"},
    { "symbol":"CRM",   "name":	"Salesforce, Inc.",	"industry":"Software - Application",	"marketCap":"309.20B"},
    { "symbol":"ABBV",  "name":	"AbbVie Inc.",	"industry":"Drug Manufacturers - General",	"marketCap":"294.35B"},
    { "symbol":"CVX",   "name": "Chevron Corporation",	"industry":"Oil & Gas Integrated",	"marketCap":"286.82B"},
    { "symbol":"SAP",   "name":	"SAP SE",	"industry":"Software - Application",	"marketCap":"270.88B"},
    { "symbol":"TMUS",  "name":	"T-Mobile US, Inc.",	"industry":"Telecom Services",	"marketCap":"270.63B"},
    { "symbol":"KO",    "name":	"The Coca-Cola Company",	"industry":"Beverages - Non-Alcoholic",	"marketCap":"269.63B"},
    { "symbol":"ASML",  "name":	"ASML Holding N.V.",	"industry":"Semiconductor Equipment & Materials",	"marketCap":"259.98B"},
    { "symbol":"WFC",   "name":	"Wells Fargo & Company",	"industry":"Banks - Diversified",	"marketCap":"244.48B"},
    { "symbol":"MRK",   "name":	"Merck & Co., Inc.",	"industry":"Drug Manufacturers - General",	"marketCap":"244.21B"},
    { "symbol":"TM",    "name":	"Toyota Motor Corporation",	"industry":"Auto Manufacturers",	"marketCap":"232.21B"},
    { "symbol":"CSCO",  "name":	"Cisco Systems, Inc.",	"industry":"Communication Equipment",	"marketCap":"227.51B"},
    { "symbol":"AMD",   "name":	"Advanced Micro Devices, Inc.",	"industry":"Semiconductors",	"marketCap":"226.20B"},
    { "symbol":"BX",    "name":	"Blackstone Inc.",	"industry":"Asset Management",	"marketCap":"225.88B"},
    { "symbol":"ACN",   "name":	"Accenture plc",	"industry":"Information Technology Services",	"marketCap":"221.17B"},
    { "symbol":"ADBE",  "name":	"Adobe Inc.",	"industry":"Software - Infrastructure",	"marketCap":"219.93B"},
    { "symbol":"PEP",   "name":	"PepsiCo, Inc.",	"industry":"Beverages - Non-Alcoholic",	"marketCap":"215.02B"},
    { "symbol":"MS",    "name":	"Morgan Stanley",	"industry":"Capital Markets",	"marketCap":"213.04B"},
    { "symbol":"LIN",   "name":	"Linde plc",	"industry":"Specialty Chemicals",	"marketCap":"211.44B"},
    { "symbol":"NOW",   "name":	"ServiceNow, Inc.",	"industry":"Software - Application",	"marketCap":"210.88B"},
    { "symbol":"MCD",   "name":	"McDonald's Corporation",	"industry":"Restaurants",	"marketCap":"208.34B"},
    { "symbol":"NVS",   "name":	"Novartis AG",	"industry":"Drug Manufacturers - General",	"marketCap":"206.29B"},
    { "symbol":"DIS",   "name":	"The Walt Disney Company",	"industry":"Entertainment",	"marketCap":"203.59B"},
    { "symbol":"ABT",   "name":	"Abbott Laboratories",	"industry":"Medical Devices",	"marketCap":"203.16B"}
]